local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: e59e7a9ca58ed745c5f76691e81cc320588dd8d15feda0cf73171703b995863a
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
